### ISSUE TITLE
tet file?

### ISSUE THREAD

**Issue by rivesa77** [PacktPublishing/Clean-Code-with-CSharp-Second-Edition#6]
https://github.com/PacktPublishing/Clean-Code-with-CSharp-Second-Edition/blob/470aa743c661ed3210cb226afe401d09350b5a57/CH03/Core/FileSystem/TextFile.cs#L47

**Comment by vidhishapackt** [comment]
Hi, it was a typo and has been fixed. Thanks for bringing this to our attention!
